### PR TITLE
feat: support scss variable interpolation

### PR DESCRIPTION
**Pull request by liuyuchenzh**
## Purpose of this pull request? 

* Enhancement

## What changes did you make?

Handle scss variable interpolation so that error won't be thrown for the following case

```scss
.a-block__#{$element} {
  display: block;
}
```

## Does this pull request introduce a breaking change?

No

## Is there anything you'd like reviewers to focus on?

 
No

### CODE REVIEW

**Comment by ernscht** [comment]
Thanks for your contribution.
You're resuming an [earlier request](https://github.com/namics/stylelint-bem-namics/issues/13)
We have said that variables are actually not linable and should therefore rather be ignored.

However, we will still look at your merge request and give you feedback as soon as possible.

**Comment by jozerozman** [comment]
@ernscht It would be great if this was implemented! Have you given it any thought? :)

**Comment by ernscht** [comment]
Sorry, I've neglected this repo terribly ;-)

Since this customisation would be "breaking" (fewer bugs would be criticised) I could only imagine integrating the feature if it's hidden behind a confguration flag.
e.g.
```
"plugin/stylelint-bem-namics": {
  "allowVariableInterpolation": true
}
```

what do you think?

**Comment by jantimon** [comment]
we do only a static code analysis. that means that we are not able to inspect the variables value so we will not be able to calculate the final selector..

adding this feature would give a wrong feeling of safety as the linter would allow any selector which includes variables even if the calculated selector would not a be a valid bem selector

**Comment by ernscht** [comment]
I would not use the feature and would not want to put any effort into it.
But if it is hidden behind a flag as suggested and includes very good test coverage, then it could be integrated - i think.

Sidenote: And then, of course, there is this possibility with the current plugin:
 ```
/* stylelint-disable plugin/stylelint-bem-namics */
.a-block__#{$element} {
  display: block;
}
/* stylelint-enable plugin/stylelint-bem-namics */
```
;-)

**Comment by janwidmer** [comment]
@ernscht I am using that quite often within mixins to get more dynamic..

**Comment by ernscht** [comment]
Valid.
I think that's exactly where it makes sense to decativite the plugin. 
Such a mixin cannot be linted this way.

**Comment by ernscht** [comment]
Will be closed due to lack of activity and unfinished work.

**Pull request closed without merging**
